#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
NOTES_DIR_NAME=".notes"
NOTES_DIR="${DIR}/../${NOTES_DIR_NAME}"

main() {
  local from=$1
  local to=$2
  if [ "$from" == "" ]; then
    from="$(date --date yesterday +%Y-%m-%d)"
  fi
  if [ "$to" == "" ]; then
    to="$(date +%Y-%m-%d)"
  fi

  local notes
  notes="$(find "${NOTES_DIR}" -type f -printf "%f\n" | awk '{ if ($1 >= "'"${from}"'" && $1 <= "'"${to}"'") print "'"${NOTES_DIR}"'/"$1 }')"

  if [ "$notes" == "" ]; then
    echo "No notes found in range ${from} => ${to}"
  else
    # shellcheck disable=SC2086
    vim -o $notes
  fi
}

main "$@"
